default: &default
  adapter: postgresql
  user: postgres
  password: password
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cc-development

test:
  <<: *default
  database: cc-test

production:
  <<: *default
  database: cc-production
